use_frameworks!

target 'Connectivity_Example' do
  pod 'Connectivity', :path => '../'

  target 'Connectivity_Tests' do
    inherit! :search_paths
    pod 'OHHTTPStubs/Swift'
    
  end
end

target 'Connectivity_Example_macOS' do
  pod 'Connectivity', :path => '../'
end
